# Generated by Django 4.1.5 on 2023-05-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('til', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.BigIntegerField()),
                ('holati', models.CharField(default='Gramatika', max_length=2000)),
                ('link', models.CharField(max_length=10000)),
                ('til', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibratapp.nom')),
            ],
        ),
    ]
